# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: codeForSofia
#subtitle:
subtitle: Open-source projects for the city of Sofia, Bulgaria.

# Title attribute of HTML Page, uses 'name' from above if empty
title: codeForSofia

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: Open-source projects for the city of Sofia, Bulgaria.
    keywords: codeForSofia, open-source, community
    crawl: index,follow

# website address when deployed, also given as canonical link
url: http://codeforsofia.org/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: '/'

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:



# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "https://avatars0.githubusercontent.com/u/8897534"
#avatar: "images/jonathan_doe.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - facebook:
      name: Facebook
      show: true
      href: https://www.facebook.com/groups/283239726751084
      icon: fab fa-facebook
  - github:
      name: GitHub
      show: true
      href: https://github.com/codeforsofia
      icon: fab fa-github
  - email:
      name: Email
      show: true
      href: mailto:codeforsofia@gmail.com
      icon: fas fa-envelope
  - publickey:
      name: PGP Key
      show: true
      href: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1bd9835e62bad0de7f5cf5508722bf2281eefc7f
      icon: fas fa-key


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:
extra_html: 

#EOF
